blank_issues_enabled: false
contact_links:
  - name: "SPSCleanVersions Discussions"
    url: https://github.com/luigilink/SPSCleanVersions/discussions
    about: "To engage with the community and maintainers of SPSCleanVersions, please visit the discussions group. There, you can share feedback, ask questions, and collaborate with others working on SPSCleanVersions."
